---
- name: Ansible modules dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - python3-pip=18.1-5+rpt1
    - virtualenv=15.1.0+ds-2
    - python-docker=3.4.1-4

- name: PiP dependencies
  pip:
    name:
      - docker==4.4.4
    state: present

- name: Folders
  file:
    state: directory
    path: "{{ item }}"
    owner: "root"
    group: "root"
    mode: 0755
  when:
    - item != "/tmp"
    - item != "/var/tmp"
  loop:
    - "{{ influxdb__path_data }}"
    - "{{ influxdb__path_config }}"

- name: SSL folder
  file:
    state: directory
    path: "{{ influxdb__path_config }}/ssl"
    owner: "root"
    group: "root"
    mode: 0755
  when: influxdb__security_ssl_enable

- name: SSL key
  copy:
    content: "{{ influxdb__security_ssl_key }}"
    dest: "{{ influxdb__path_config }}/ssl/influxdb.key"
    owner: "root"
    group: "root"
    mode: 0600
  when: influxdb__security_ssl_enable
  notify:
    - Restart Systemd service

- name: SSL certificate
  copy:
    content: "{{ influxdb__security_ssl_crt }}"
    dest: "{{ influxdb__path_config }}/ssl/influxdb.crt"
    owner: "root"
    group: "root"
    mode: 0644
  when: influxdb__security_ssl_enable
  notify:
    - Restart Systemd service

- name: Configuration file
  template:
    src: "influxdb.conf.j2" 
    dest: "{{ influxdb__path_config }}/influxdb.conf"
    owner: "root"
    group: "root"
    mode: 0644
  notify:
    - Restart Systemd service

- name: Create Docker containter
  docker_container:
    name: influxdb
    image: "{{ influxdb__docker_image }}:{{ influxdb__docker_tag }}"
    state: present
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "{{ influxdb__path_data }}:/var/lib/influxdb"
      - "{{ influxdb__path_config }}:/etc/influxdb"
    ports:
      - "8086:8086"
  notify:
    - Restart Systemd service

- name: Systemd service file
  copy:
    src: docker/influxdb.service
    dest: /lib/systemd/system/influxdb.service
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart Systemd service
...
