---
- name: Linux deployment
  import_tasks: linux.yml
  when: influxdb__deployment_mode == 'linux'

- name: Docker deployment
  import_tasks: docker.yml
  when: influxdb__deployment_mode == 'docker'

- name: Flush handlers
  meta: flush_handlers

- name: Wait for API availability
  wait_for:
    port: 8086
    delay: 10

- name: Internal configuration
  import_tasks: configure.yml
...
